### PR TITLE
Added autobiographical number

### PR DESCRIPTION
**Pull request by akarshan2602**
added the code for autobiographical number, also explained a little bit about the same

### CODE REVIEW

**Comment by drishyadamodaran** [comment]
add to the correct folder

**Review by drishyadamodaran — CHANGES_REQUESTED** [review]
add to the correct folders

**Comment by akarshan2602** [comment]
I did, i think i added it to competitive programming?

**Comment by akarshan2602** [comment]
> add to the correct folders

I did, i added to competitive programming folder under the folder PYTHON

**Review by drishyadamodaran — APPROVED** [review]

**Comment by drishyadamodaran** [comment]
approved #53

**Comment by akarshan2602** [comment]
Thanks! Be sure to add the hacktober label!

**Pull request merged**
